# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aed884369dffb9e6a40dd9111bed14f898158afbdfeb5aba04114dc6eb36263e071ecd57d83c1e431ea9632ce4e9c7001da085a8bb0df80da070203fe3c3169

test:
  secret_key_base: 0eefaa458f90866aa199eed8e32610909e1d1f6741653050c402a6fcc1f758a7a9b556b943e82eacc2a3a8720618fee69670fb932fb181077e8c94c59b18466b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
